name: mtpc
base: core18
version: '1.0'
summary: Pyhton multithread HTTP post
description: |
  Just a simple test application

grade: devel
confinement: devmode

architectures:
  - build-on: [amd64, i386]
    run-on: all

parts:
  mtpc:
    source: .
    plugin: python
    python-version: python3

apps:
  mtpc:
    command: python3 mtpc.py
